### ISSUE TITLE
Question mark on the right side (when showing a trailing warning)

### ISSUE THREAD

**Issue by highend** [nicolalamacchia/powerline-consolas#4]
Hi,

It's not directly related to powerline because I'm using vim-airline but the visual glitch is probably the same...

Win 7 Ultimate SP1
Latest powerline-consolas & vim-airline version

I've overwritten the original consolas font and everything in the status line looks fine (this is by far the best working font for it!).

Only when vim-airline shows a warning on the right side (in this case the file has trailing whitespaces), the left side of it shows only a small question mark in a box.

I'm unsure which symbol should be there but I guess it's not the one I currently have :)

Maybe you could take a look at it if you get the same behavior?

Screenshot:
![unbenannt-1](https://f.cloud.github.com/assets/687706/1423525/800ea7b6-400c-11e3-8fd1-9274fad866b5.png)

**Comment by nicolalamacchia** [comment]
Hi,
as I said [here](https://github.com/nicolalamacchia/powerline-consolas/issues/3), you should consider this font to only work with the official Powerline.

Anyway, this is odd. AFAIK the default symbol for trailing spaces in Airline is an exclamation mark. Try to change it, here is what I have in my `vimrc`: `let g:airline#extensions#whitespace#symbol = '␣'`. Maybe you've got a version of Airline with a different default symbol for trailing whitespaces.

Let me know how you solve it.

**Comment by highend** [comment]
Hi,

I've patched (in fact I've modified only a few entries for the font name) your font a second time. So I don't need to overwrite the original one. Guess what? I works now, no question mark anymore. Don't ask me why I didn't change any glyphs inside the font nor any of my vim settings...
